### ISSUE TITLE
Work tracked in Patio

### ISSUE THREAD

**Issue by arengel** [rmi-electricity/gencost#76]
rmi-electricity/patio-model#1

- [ ] rmi-electricity/patio-model#88
- [ ] rmi-electricity/patio-model#89
- [ ] rmi-electricity/patio-model#90
- [ ] rmi-electricity/patio-model#77
- [ ] rmi-electricity/patio-model#78
- [ ] rmi-electricity/patio-model#86
- [ ] rmi-electricity/patio-model#85
- [ ] rmi-electricity/patio-model#80
- [ ] rmi-electricity/patio-model#81
- [ ] rmi-electricity/patio-model#82
- [ ] rmi-electricity/patio-model#83
- [ ] rmi-electricity/patio-model#84
